### ISSUE TITLE
ImportError after install

### ISSUE THREAD

**Issue by DragonlordNewb** [skelsec/pypykatz#120]
I'm running Python 3.10.0 on a Windows 11 machine. When I try and run the module, I get the following error - 
```
> py -m pypykatz
Traceback (most recent call last):
  File "C:\Users\data expunged\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\data expunged\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\data expunged\AppData\Local\Programs\Python\Python310\lib\site-packages\pypykatz\__main__.py", line 156, in <module>
    main()
  File "C:\Users\data expunged\AppData\Local\Programs\Python\Python310\lib\site-packages\pypykatz\__main__.py", line 17, in main
    from pypykatz.kerberos.cmdhelper import KerberosCMDHelper
  File "C:\Users\data expunged\AppData\Local\Programs\Python\Python310\lib\site-packages\pypykatz\kerberos\cmdhelper.py", line 19, in <module>
    from pypykatz.kerberos.kerberos import get_TGS, get_TGT, generate_targets, \
  File "C:\Users\data expunged\AppData\Local\Programs\Python\Python310\lib\site-packages\pypykatz\kerberos\kerberos.py", line 7, in <module>
    from minikerberos.security import KerberosUserEnum, APREPRoast, Kerberoast
ImportError: cannot import name 'KerberosUserEnum' from 'minikerberos.security' (C:\Users\data expunged\AppData\Local\Programs\Python\Python310\lib\site-packages\minikerberos-0.4.0-py3.10.egg\minikerberos\security.py)
```
bad import name? cuz I also couldn't find "KerberosUserEnum" anywhere in the `minikerberos` repo.
If absolutely necessary I wouldn't mind switching to my Windows 10 machine or upgrading Python but I'd rather not if possible.

**Comment by skelsec** [comment]
The issue was caused that I published the new version of `minikerberos` package but not the new version of `pypykatz`.  
It is fixed now

**Comment by QU35T-code** [comment]
https://github.com/skelsec/pypykatz/issues/117
