### ISSUE TITLE
AttributeError: 'collections.OrderedDict' object has no attribute 'kirbiobj'

### ISSUE THREAD

**Issue by CaledoniaProject** [skelsec/pypykatz#126]
Looks like a bug, can you fix it? I can't provide the minidump.

```
INFO:pypykatz:===== BASIC INFO. SUBMIT THIS IF THERE IS AN ISSUE =====
INFO:pypykatz:pypyKatz version: 0.3.13
INFO:pypykatz:CPU arch: X64
INFO:pypykatz:OS: Windows Server 2012 R2
INFO:pypykatz:BuildNumber: 9600
INFO:pypykatz:MajorVersion: 6
INFO:pypykatz:MSV timestamp: 1518281322
INFO:pypykatz:===== BASIC INFO END =====
ERROR:root:Error while parsing file lsass.DMP
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pypykatz/lsadecryptor/cmdhelper.py", line 195, in run
    mimi = pypykatz.parse_minidump_file(args.memoryfile)
  File "/usr/local/lib/python3.6/dist-packages/pypykatz/pypykatz.py", line 119, in parse_minidump_file
    raise e
  File "/usr/local/lib/python3.6/dist-packages/pypykatz/pypykatz.py", line 115, in parse_minidump_file
    mimi.start()
  File "/usr/local/lib/python3.6/dist-packages/pypykatz/pypykatz.py", line 311, in start
    self.get_kerberos()
  File "/usr/local/lib/python3.6/dist-packages/pypykatz/pypykatz.py", line 298, in get_kerberos
    self.kerberos_ccache.add_kirbi(ticket.kirbi_data[fn].native)
  File "/usr/local/lib/python3.6/dist-packages/minikerberos/common/ccache.py", line 613, in add_kirbi
    c = Credential.from_kirbi(kirbi)
  File "/usr/local/lib/python3.6/dist-packages/minikerberos/common/ccache.py", line 182, in from_kirbi
    krbcred = kirbi.kirbiobj.native
AttributeError: 'collections.OrderedDict' object has no attribute 'kirbiobj'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pypykatz/lsadecryptor/cmdhelper.py", line 195, in run
    mimi = pypykatz.parse_minidump_file(args.memoryfile)
  File "/usr/local/lib/python3.6/dist-packages/pypykatz/pypykatz.py", line 119, in parse_minidump_file
    raise e
  File "/usr/local/lib/python3.6/dist-packages/pypykatz/pypykatz.py", line 115, in parse_minidump_file
    mimi.start()
  File "/usr/local/lib/python3.6/dist-packages/pypykatz/pypykatz.py", line 311, in start
    self.get_kerberos()
  File "/usr/local/lib/python3.6/dist-packages/pypykatz/pypykatz.py", line 298, in get_kerberos
    self.kerberos_ccache.add_kirbi(ticket.kirbi_data[fn].native)
  File "/usr/local/lib/python3.6/dist-packages/minikerberos/common/ccache.py", line 613, in add_kirbi
    c = Credential.from_kirbi(kirbi)
  File "/usr/local/lib/python3.6/dist-packages/minikerberos/common/ccache.py", line 182, in from_kirbi
    krbcred = kirbi.kirbiobj.native
AttributeError: 'collections.OrderedDict' object has no attribute 'kirbiobj'
```

**Comment by skelsec** [comment]
Hello!
Based on the error the pypykatz version you're using is `0.3.13` which was finalized 4 years ago. The current one is `0.6.6`.  
Can you try to upgrade to the current version and check if it solves your issue?

**Comment by CaledoniaProject** [comment]
Yes, that was weird. I'm using python3.6 and it automatically installed an old version.
