### ISSUE TITLE
pypykatz dpapi blob fails

### ISSUE THREAD

**Issue by ProximaCentauri1989** [skelsec/pypykatz#170]
Hello. Is it possible that pypykatz can't decode files from identity cache?

My command
pypykatz dpapi blob C:\Users\<user>\mkf.json C:\Users\<user>\AppData\Local\Microsoft\IdentityCache\1\UD\u_441G1KG8SN3V2EP7\e_C2GK9UTC67FSUCG3\AT\r_74DB6FURNR2TGPBK\c_CIKANBVJ4RSF161D.bin

Result:
Traceback (most recent call last):
  File "C:\Users\docker\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\docker\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\docker\AppData\Local\Programs\Python\Python310\Scripts\pypykatz.exe\__main__.py", line 7, in <module>
  File "C:\Users\docker\AppData\Local\Programs\Python\Python310\lib\site-packages\pypykatz\__main__.py", line 89, in main
    helper.execute(args)
  File "C:\Users\docker\AppData\Local\Programs\Python\Python310\lib\site-packages\pypykatz\dpapi\cmdhelper.py", line 151, in execute
    self.run(args)
  File "C:\Users\docker\AppData\Local\Programs\Python\Python310\lib\site-packages\pypykatz\dpapi\cmdhelper.py", line 277, in run
    dec_sec = dpapi.decrypt_securestring_file(args.blob)
  File "C:\Users\docker\AppData\Local\Programs\Python\Python310\lib\site-packages\pypykatz\dpapi\dpapi.py", line 562, in decrypt_securestring_file
    data = f.read()
  File "C:\Users\docker\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 6: character maps to <undefined>

For some reasons pypykatz unable to read file but mimikatz did just fine and get me everything without any error.

**Comment by hb9tst** [comment]
`pypykatz dpapi blob` expects data in hexadecimal form, not a binary blob. This is probably the reason the decoding is failing. Reading binary blobs would be a convenient feature to add, though...
