### ISSUE TITLE
Exception: Failed to find lsass.exe

### ISSUE THREAD

**Issue by danielhnmoreno** [skelsec/pypykatz#25]
Cmd with administrator privileges:

C:\Users\Usuario\Downloads\pypykatz-master>**pypykatz.exe live lsa**

Exception while dumping LSA credentials from memory.
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python37\lib\site-packages\pypykatz-0.0.7-py3.7.egg\pypykatz\__main__.py", line 74, in main
    mimi = pypykatz.go_live()
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python37\lib\site-packages\pypykatz-0.0.7-py3.7.egg\pypykatz\pypykatz.py", line 44, in go_live
    reader = LiveReader()
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python37\lib\site-packages\pypykatz-0.0.7-py3.7.egg\pypykatz\commons\readers\local\live_reader.py", line 308, in __init__
    self.setup()
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python37\lib\site-packages\pypykatz-0.0.7-py3.7.egg\pypykatz\commons\readers\local\live_reader.py", line 344, in setup
    pid = get_lsass_pid()
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python37\lib\site-packages\pypykatz-0.0.7-py3.7.egg\pypykatz\commons\readers\local\common\live_reader_ctypes.py", line 78, in get_lsass_pid
    raise Exception('Failed to find lsass.exe')
**Exception: Failed to find lsass.exe**

==== Parsing errors:
live

**Comment by skelsec** [comment]
Send a bit more details if possible.
Like... what Windows version is that? Buildnumber? Are there any processes running that might interfere (eg. endpoint security, AV etc)?

**Comment by danielhnmoreno** [comment]
Windows 10 Home 64 bits 

NO AV

C:\Users\Usuario>**systeminfo**

Nome do host:                              DESKTOP-MFB3E88
Nome do sistema operacional:               Microsoft Windows 10 Home Single Language
Versão do sistema operacional:             **10.0.17763 N/A compilação 17763**

**Comment by skelsec** [comment]
Closing this, as I can't reproduce it. 
Double-checked the code and it was finding the lsass.exe 100% of the time.

**Comment by WTCXY** [comment]
C:\Users\test\Desktop>pypykatz live lsa
Exception while dumping LSA credentials from memory.
Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Programs\Python\Python313\Lib\site-packages\pypykatz\lsadecryptor\cmdhelper.py", line 186, in run_live
    mimi = pypykatz.go_live(packages=args.packages)
  File "C:\Users\test\AppData\Local\Programs\Python\Python313\Lib\site-packages\pypykatz\pypykatz.py", line 105, in go_live
    reader = LiveReader()
  File "C:\Users\test\AppData\Local\Programs\Python\Python313\Lib\site-packages\pypykatz\commons\readers\local\live_reader.py", line 314, in __init__
    self.setup()
    ~~~~~~~~~~^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python313\Lib\site-packages\pypykatz\commons\readers\local\live_reader.py", line 350, in setup
    self.process_pid = pid_for_name(self.process_name)
                       ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\test\AppData\Local\Programs\Python\Python313\Lib\site-packages\pypykatz\commons\readers\local\common\live_reader_ctypes.py", line 208, in pid_for_name
    raise Exception('Failed to find %s' % process_name)
Exception: Failed to find lsass.exe

==== Parsing errors:
live
