### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by AndyXan** [skelsec/pypykatz#28]
Hello, 

I am reporting a parsing error problem with a recent Windows 10 dump as `nt authority/system` with `.\procdump.exe -accepteula -ma lsass.exe lsass.dmp` from `sysinternals suite`.  Sadly at the time I cannot provide the dump as this is a live environment and I don't know if passwords are stored or not. Maybe this is enough to investigate, if not I'll try to setup a equivalent Windows 10 Demo Environment without any sensitive information to reproduce the problem.

```
pypykatz -v lsa minidump -e -o test.txt /media/sf_VM_Shared/lsass_dump/lsass.dmp 
INFO:root:Parsing file /media/sf_VM_Shared/lsass_dump/lsass.dmp
DEBUG:root:Found ThreadListStream @684 Size: 436
DEBUG:root:Found ThreadInfoListStream @838 Size: 588
DEBUG:root:== ThreadInfoList ==
ThreadId | DumpFlags | DumpError | ExitStatus | CreateTime         | ExitTime | KernelTime | UserTime | StartAddress   | Affinity
---------------------------------------------------------------------------------------------------------------------------------
0x328    | None      | 0         | 0x103      | 132107882520296581 | 0        | 0          | 0        | 0x7ff692874080 | 255     
0x350    | None      | 0         | 0x103      | 132107882520443197 | 0        | 0          | 468750   | 0x7ffb24f570b0 | 255     
0x358    | None      | 0         | 0x103      | 132107882520484094 | 0        | 0          | 0        | 0x7ffb292dff80 | 255     
0x374    | None      | 0         | 0x103      | 132107882521355310 | 0        | 0          | 0        | 0x7ffb282db140 | 255     
0x1be4   | None      | 0         | 0x103      | 132107882605183752 | 0        | 156250     | 0        | 0x7ffafb39a2b0 | 255     
0x37c4   | None      | 0         | 0x103      | 132108423879863795 | 0        | 12656250   | 12343750 | 0x7ffb292dff80 | 255     
0x393c   | None      | 0         | 0x103      | 132108509461476735 | 0        | 0          | 0        | 0x7ffb292dff80 | 255     
0x3a7c   | None      | 0         | 0x103      | 132108512512415381 | 0        | 781250     | 0        | 0x7ffb292dff80 | 255     
0x22e4   | None      | 0         | 0x103      | 132108513655868506 | 0        | 156250     | 0        | 0x7ffb292dff80 | 255     

DEBUG:root:Found ModuleListStream @a84 Size: 10912
DEBUG:root:Found UnloadedModuleListStream @3524 Size: 396
DEBUG:root:Found TokenStream @36b0 Size: 704
DEBUG:root:TokenStream parsing is not implemented (Missing documentation)
DEBUG:root:Found Memory64ListStream @41e29 Size: 10704
DEBUG:root:Found MemoryInfoListStream @36bc9 Size: 45664
DEBUG:root:Found SystemInfoStream @f8 Size: 56
DEBUG:root:Found MiscInfoStream @130 Size: 1364
DEBUG:root:Found HandleDataStream @21e71 Size: 85336
DEBUG:root:Found SystemMemoryInfoStream @3970 Size: 492
DEBUG:root:SystemMemoryInfoStream parsing is not implemented (Missing documentation)
DEBUG:root:Found ProcessVmCountersStream @3b5c Size: 152
DEBUG:root:ProcessVmCountersStream parsing is not implemented (Missing documentation)
DEBUG:root:Found CommentStreamW @949d Size: 242
DEBUG:root:Found UnusedStream @0 Size: 0
DEBUG:root:Found UnusedStream @0 Size: 0
DEBUG:root:Found UnusedStream @0 Size: 0
DEBUG:root:Found UnusedStream @0 Size: 0
DEBUG:root:Found UnusedStream @0 Size: 0
DEBUG:pypykatz:===== BASIC INFO. SUBMIT THIS IF THERE IS AN ISSUE =====
DEBUG:pypykatz:CPU arch: X64
DEBUG:pypykatz:OS: Windows 10
DEBUG:pypykatz:BuildNumber: 17763
DEBUG:pypykatz:MajorVersion: 6 
DEBUG:pypykatz:MSV timestamp: 412103479
DEBUG:pypykatz:===== BASIC INFO END =====
ERROR:root:Error while parsing file /media/sf_VM_Shared/lsass_dump/lsass.dmp
Traceback (most recent call last):
  File "/home/wittmann/ReverseTools/windows/pypykatz/pypykatz/lsadecryptor/cmdhelper.py", line 169, in run
    mimi = pypykatz.parse_minidump_file(args.memoryfile)
  File "/home/wittmann/ReverseTools/windows/pypykatz/pypykatz/pypykatz.py", line 56, in parse_minidump_file
    mimi.start()
  File "/home/wittmann/ReverseTools/windows/pypykatz/pypykatz/pypykatz.py", line 168, in start
    self.lsa_decryptor = self.get_lsa()
  File "/home/wittmann/ReverseTools/windows/pypykatz/pypykatz/pypykatz.py", line 98, in get_lsa
    lsa_dec = LsaDecryptor(self.reader, lsa_dec_template, self.sysinfo)
  File "/home/wittmann/ReverseTools/windows/pypykatz/pypykatz/lsadecryptor/lsa_decryptor.py", line 21, in __init__
    self.acquire_crypto_material()
  File "/home/wittmann/ReverseTools/windows/pypykatz/pypykatz/lsadecryptor/lsa_decryptor.py", line 29, in acquire_crypto_material
    self.iv = self.get_IV(sigpos)
  File "/home/wittmann/ReverseTools/windows/pypykatz/pypykatz/lsadecryptor/lsa_decryptor.py", line 57, in get_IV
    self.reader.move(ptr_iv)
  File "/home/wittmann/.virtualenvs/cpython3/lib/python3.6/site-packages/minidump/minidumpreader.py", line 84, in move
    self._select_segment(address)
  File "/home/wittmann/.virtualenvs/cpython3/lib/python3.6/site-packages/minidump/minidumpreader.py", line 55, in _select_segment
    raise Exception('Memory address 0x%08x is not in process memory space' % requested_position)
Exception: Memory address 0x7ffb6dbc6267 is not in process memory space

```

**Comment by skelsec** [comment]
a lot has changed since a few weeks in the code, can you please let me know which version you are using? did you install from pip or from github?

**Comment by skelsec** [comment]
also, since it's not possible to provide test dumps you can still help by testing it on different versions if you have time

**Comment by AndyXan** [comment]
Hello, 

sry for the late reply. I'm going to do as you said and test it with other versions as soon as I have some free time. Propbably end of Sept. I'd keep the issue open for the time being, if you don't mind.

**Comment by skelsec** [comment]
sure no problem.

**Comment by skelsec** [comment]
no response since, closing.
