### ISSUE TITLE
During parsing of registry hives: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by AdrianVollmer** [skelsec/pypykatz#40]
I'm using version 0.3.3. Below is the  full message. The command was `pypykatz registry system.dat --sam sam.dat`.

What do you think about replacing `aiowinreg/filestruct/nk.py:96` with this line:
```
    nk.name = nk.name.decode(encoding, "backslashreplace")
```
Then it might insert something like `\xe4` somewhere in the output, but at least the program won't crash. Not sure if it doesn't break something else though.

```
# pypykatz  registry system.dat --sam sam.dat
WARNING:pypykatz:SECURITY hive path not supplied! Parsing SECURITY will not work
WARNING:pypykatz:SOFTWARE hive path not supplied! Parsing SOFTWARE will not work
Traceback (most recent call last):
  File "/root/.local/bin/pypykatz", line 10, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.7/site-packages/pypykatz/__main__.py", line 133, in main
    helper.execute(args)
  File "/root/.local/lib/python3.7/site-packages/pypykatz/registry/cmdhelper.py", line 38, in execute
    self.run(args)
  File "/root/.local/lib/python3.7/site-packages/pypykatz/registry/cmdhelper.py", line 73, in run
    po = OffineRegistry.from_files(args.system, args.sam, args.security, args.software)
  File "/root/.local/lib/python3.7/site-packages/pypykatz/registry/offline_parser.py", line 171, in from_files
    po.get_secrets()
  File "/root/.local/lib/python3.7/site-packages/pypykatz/registry/offline_parser.py", line 41, in get_secrets
    self.sam.get_secrets()
  File "/root/.local/lib/python3.7/site-packages/pypykatz/registry/sam/sam.py", line 117, in get_secrets
    self.get_HBoot_key()
  File "/root/.local/lib/python3.7/site-packages/pypykatz/registry/sam/sam.py", line 69, in get_HBoot_key
    F = self.hive.get_value(r'SAM\Domains\Account\F')[1]
  File "/root/.local/lib/python3.7/site-packages/aiowinreg/hive.py", line 123, in get_value
    self.setup()
  File "/root/.local/lib/python3.7/site-packages/aiowinreg/hive.py", line 28, in setup
    self.root = self.search_root_key()
  File "/root/.local/lib/python3.7/site-packages/aiowinreg/hive.py", line 39, in search_root_key
    hbin = NTRegistryHbin.read(self.reader)
  File "/root/.local/lib/python3.7/site-packages/aiowinreg/filestruct/hbin.py", line 49, in read
    cell = NTRegistryCell.read(reader)
  File "/root/.local/lib/python3.7/site-packages/aiowinreg/filestruct/regcell.py", line 34, in read
    cell.data = NTRegistryKeyTypes[cell.data[:2]].from_bytes(cell.data)
  File "/root/.local/lib/python3.7/site-packages/aiowinreg/filestruct/nk.py", line 67, in from_bytes
    return NTRegistryNK.from_buffer(io.BytesIO(data))
  File "/root/.local/lib/python3.7/site-packages/aiowinreg/filestruct/nk.py", line 98, in from_buffer
    raise e
  File "/root/.local/lib/python3.7/site-packages/aiowinreg/filestruct/nk.py", line 96, in from_buffer
    nk.name = nk.name.decode(encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 1: ordinal not in range(128)
```

**Comment by AdrianVollmer** [comment]
Some more info: it fails when decoding the byte string `b'G\xe4ste'`, which "Gäste", the German word for "Guests". I believe then the encoding we should be using here is `iso-8859-15` instead of `ascii`. 

However, I'm also realizing that I should have submitted this to https://github.com/skelsec/aiowinreg.

So consider this PR: https://github.com/skelsec/aiowinreg/pull/1

**Comment by skelsec** [comment]
I have merged the PR in aiowinreg, thank you for the contribution
