### ISSUE TITLE
UnicodeDecodeError in aiowinreg module

### ISSUE THREAD

**Issue by jarlethorsen** [skelsec/pypykatz#44]
Thank you very much for a great project. So far I have found it very well structured and easy to import in my own projects.

I realize this error is located in an external module, but I just wanted to bring it to your attention in case there is something you can do mitigate the error in your code:

```
$ python3
Python 3.7.6 (default, Jan 30 2020, 10:29:04) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pypykatz.registry.offline_parser import OffineRegistry
>>> po = OffineRegistry.from_files('SYSTEM', 'SAM')
SECURITY hive path not supplied! Parsing SECURITY will not work
SOFTWARE hive path not supplied! Parsing SOFTWARE will not work
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pypykatz-0.3.5-py3.7.egg/pypykatz/registry/offline_parser.py", line 171, in from_files
  File "/usr/local/lib/python3.7/site-packages/pypykatz-0.3.5-py3.7.egg/pypykatz/registry/offline_parser.py", line 41, in get_secrets
  File "/usr/local/lib/python3.7/site-packages/pypykatz-0.3.5-py3.7.egg/pypykatz/registry/sam/sam.py", line 117, in get_secrets
  File "/usr/local/lib/python3.7/site-packages/pypykatz-0.3.5-py3.7.egg/pypykatz/registry/sam/sam.py", line 69, in get_HBoot_key
  File "/usr/local/lib/python3.7/site-packages/aiowinreg-0.0.2-py3.7.egg/aiowinreg/hive.py", line 123, in get_value
    self.setup()
  File "/usr/local/lib/python3.7/site-packages/aiowinreg-0.0.2-py3.7.egg/aiowinreg/hive.py", line 28, in setup
    self.root = self.search_root_key()
  File "/usr/local/lib/python3.7/site-packages/aiowinreg-0.0.2-py3.7.egg/aiowinreg/hive.py", line 39, in search_root_key
    hbin = NTRegistryHbin.read(self.reader)
  File "/usr/local/lib/python3.7/site-packages/aiowinreg-0.0.2-py3.7.egg/aiowinreg/filestruct/hbin.py", line 49, in read
    cell = NTRegistryCell.read(reader)
  File "/usr/local/lib/python3.7/site-packages/aiowinreg-0.0.2-py3.7.egg/aiowinreg/filestruct/regcell.py", line 34, in read
    cell.data = NTRegistryKeyTypes[cell.data[:2]].from_bytes(cell.data)
  File "/usr/local/lib/python3.7/site-packages/aiowinreg-0.0.2-py3.7.egg/aiowinreg/filestruct/nk.py", line 67, in from_bytes
    return NTRegistryNK.from_buffer(io.BytesIO(data))
  File "/usr/local/lib/python3.7/site-packages/aiowinreg-0.0.2-py3.7.egg/aiowinreg/filestruct/nk.py", line 98, in from_buffer
    raise e
  File "/usr/local/lib/python3.7/site-packages/aiowinreg-0.0.2-py3.7.egg/aiowinreg/filestruct/nk.py", line 96, in from_buffer
    nk.name = nk.name.decode(encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 1: ordinal not in range(128)
>>> 
```
Unfortunately I'm not able to share a copy of the offending SAM file. The code works fine for other data.

Please let me know if there is anything more I can do to help debug.

I guess it may be related with unicode chars in the username? The SAM contains the following usernames:

Administratör
Gäst

**Comment by jarlethorsen** [comment]
ohh, I realized that aiowinreg is also a project by you. Maybe this should be a aiowinreg issue instead of a pypykatz issue then ?

**Comment by jarlethorsen** [comment]
This issue was fixed in aiowinreg master (https://github.com/skelsec/aiowinreg/commit/5b3cc70b02b1134ecabc414547f258e618015808) however this fix was not available in the version installed from pip by running:
python3 setup.py install on pypykatz

You may close this issue, but maybe update the version of aiowinreg installed via pip?

**Comment by skelsec** [comment]
You are a lifesaver, I totally forgot to update the aiowinreg module.
Now it has been updated, and also the requirement in pypykatz's setup.py is bumped so it should work now perfectly from pip as well.
Please confirm and close or let me know if it's still crasing

**Comment by jarlethorsen** [comment]
I can confirm that running a "python3 setup.py install" on latest github version of aiowinreg fixed the bug here. I have not tested the updated pip version, but I see no reason why this should not work as well. I close this issue.
