### ISSUE TITLE
Live option available on Linux

### ISSUE THREAD

**Issue by mubix** [skelsec/pypykatz#72]
Just a suggestion, but the live option should provide some sort of checking to see if there is an LSASS process available. When it's run on Linux, (I'm not sure if using it on WSL1 would work, cool possibility there) , but if it's can't find LSASS.exe running in a process list it might be worth erroring out with a mention that `live` is only for `localhost` and can't be used for remote access of LSASS

**Comment by mubix** [comment]
Sort of how it is for HandleDup
```
root@ubuntu:~# pypykatz live lsa --method handledup
Exception while dumping LSA credentials from memory.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pypykatz/lsadecryptor/cmdhelper.py", line 151, in run_live
    mimi = pypykatz.go_handledup()
  File "/usr/local/lib/python3.8/dist-packages/pypykatz/pypykatz.py", line 96, in go_handledup
    raise Exception('Live parsing will only work on Windows')
Exception: Live parsing will only work on Windows

==== Parsing errors:
live
```

**Comment by mubix** [comment]
Closed because while it does print a stack trace, it does have the notice that it only works on Windows.
